### PR TITLE
Change dividesDef to Divides a b :- (Mod b a ~ 0)

### PR DESCRIPTION
**Pull request by Bodigrim**
As discussed in #96

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Thanks. Since this is a breaking change, can you also increase the version number to `0.12` in `constraints.cabal`?

I think it would also be a good idea to leave a comment somewhere neat `dividesDef` that explains why the current type was chosen.

**Comment by Bodigrim** [comment]
Done.

**Comment by RyanGlScott** [comment]
Thanks, @Bodigrim. I was going through the changelog and planning to add a brief mention of how to define the old version of `dividesDef` in terms of the old one, but I realized that I don't know how to do so. This was my attempt:

```hs
dividesDef' :: forall a b. Divides a b :- ((a * Div b a) ~ b)
dividesDef' = Sub $ case (dividesDef @a @b, euclideanNat @a @b) of
  (Sub Dict, Sub Dict) -> Dict
```

But this doesn't typecheck, since `euclideanNat` requires `1 <= a`:

```
error:
    • Could not deduce: (1 <=? a) ~ 'True arising from a pattern
      from the context: a ~ Gcd a b
        bound by a type expected by the context:
                   (a ~ Gcd a b) => Dict ((a * Div b a) ~ b)
        at <interactive>:22:84-158
      or from: Mod b a ~ 0
        bound by a pattern with constructor:
                   Dict :: forall (a :: Constraint). a => Dict a,
                 in a case alternative
        at <interactive>:22:136-139
    • In the pattern: Dict
      In the pattern: Sub Dict
      In the pattern: (Sub Dict, Sub Dict)
    • Relevant bindings include
        dividesDef' :: Divides a b :- ((a * Div b a) ~ b)
          (bound at <interactive>:22:64)
```

How did you accomplish this?

**Comment by Bodigrim** [comment]
You need `1 <= a` in scope, sorry for not being clear enough. As mentioned in #96, `Divides 0 0` is weird anyways. 

One can separately prove
```haskell
dividesDef0 :: forall b. Divides 0 b :- ((0 * Div b 0) ~ b)
dividesDef0 = Sub $ case gcdZero @b of
  Dict -> Dict
```
but I do not know how to combine it neatly with 
```haskell
dividesDef' :: forall a b. (1 <= a, Divides a b) :- ((a * Div b a) ~ b)
dividesDef' = Sub $ case (dividesDef @a @b, euclideanNat @a @b) of
  (Sub Dict, Sub Dict) -> Dict
```
restoring `forall a b. Divides a b :- ((a * Div b a) ~ b)`.

It would be helpful to have something of sort
```haskell
{-# LANGUAGE GADTs               #-}
{-# LANGUAGE ScopedTypeVariables #-}

import Data.Proxy
import Data.Type.Equality
import GHC.TypeNats
import Unsafe.Coerce

decompose0 :: forall a. KnownNat a => Proxy a -> Either (a :~: 0) ((1 <=? a) :~: 'True)
decompose0 p = case p `sameNat` (Proxy :: Proxy 0) of
  Just Refl -> Left Refl
  Nothing   -> Right (unsafeCoerce Refl)
```
or even a more general version, returning basically
```haskell
data NatOrdering a b where 
  NatLT :: CmpNat a b ~ 'LT => NatOrdering a b 
  NatEQ :: CmpNat a b ~ 'EQ => NatOrdering a b 
  NatGT :: CmpNat a b ~ 'GT => NatOrdering a b 
```

**Comment by RyanGlScott** [comment]
Ah, so the `1 <= a` requirement is intentional—thanks for clarifying.

**Pull request merged**
