### PR TITLE
Allow building with bundled version of binary on GHC-7.8.4

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
I have a very silly question: where exactly in `constraints` is the `Binary Natural` instance used?

**Comment by phadej** [comment]
It's not silly, it;s good.

`binary` dependency were introduced in 3edd3c2bb9dce2571e9d071cd4d5bad4d7ebf1c7

Let me run some tests. I somehow assumed `Binary Natural` is the reason, as pre GHC-7.8 (without TypeNats) support is dropped

**Comment by phadej** [comment]
After further investigation I haven't found a reason to have original binary lower bound, so now it's unconditionally relaxed. OTOH I found too lax lower bounds for `semigroups`, `transformers` and `transformers-compat`, so they are bumped. And as consequence also `mtl` (as there aren't valid install-plans for `mtl-2.0`)

**Comment by RyanGlScott** [comment]
This looks great. Thanks for investigating!

**Pull request merged**
