### PR TITLE
Restrict kind of `ForallT`

### PR DESCRIPTION
**Pull request by oerjan**
As I understand it, Sjoerd Visscher contributed `ForallT` to be useful with transformers, and uses it
in his own [free-functors](https://github.com/sjoerdvisscher/free-functors) package. I test compiled it, and the new `ForallT` breaks it.

The old kind of ForallT was
```haskell
ForallT :: (* -> Constraint) -> ((* -> *) -> * -> *) -> Constraint
```
while the new kind is
```haskell
ForallT :: (k -> Constraint) -> (k1 -> k2 -> k) -> Constraint
```
The latter does not default to the former without `PolyKinds`, which means type signatures get wrongly interpreted unless they're written with explicit kinds.

The same issue might happen again whenever someone tries to use `ForallT` with general type variables that are intended but not explicitly restricted to be transformers, without `PolyKinds` enabled.

This commit restricts the kind just enough that it defaults to the old one when `PolyKinds` is
off.

### CODE REVIEW

**Comment by oerjan** [comment]
Of course if you think the new kind is still better, I can always write a pull request to him instead.

**Comment by sjoerdvisscher** [comment]
Thanks for trying it out! I am fine with updating my code.

**Comment by ekmett** [comment]
I have no objection to doing this, though I think the Forall guts have changed quite a bit since this was written.

**Comment by ekmett** [comment]
I've implemented a functionally equivalent patch for the current Forall approach, I believe.

**Pull request closed without merging**
