### PR TITLE
Drop type-equality dependency

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Thanks, @phadej!

The commit message mentions that this is a WIP. Do you still plan to make further changes?

**Comment by phadej** [comment]
> The commit message mentions that this is a WIP. Do you still plan to make further changes?

No, I think it's good as it is, if you don't want to cleanup it later (i.e. remove `as Hetero`). But as it stands now it's a minimal patch.

**Review by RyanGlScott — APPROVED** [review]
Ah, OK. In that case, I'll use GitHub's squash-and-merge feature to remove the WIP part from the commit message. Thanks!

**Comment by RyanGlScott** [comment]
I've uploaded [`constraints-0.14.1`](https://hackage.haskell.org/package/constraints-0.14.1) to Hackage with these changes.

**Pull request merged**
